version: '3'

services:
  db:
    image: redis:alpine
    command: redis-server appendonly yes
    ports: 
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis_data:/data

  shortener:
    build: ./
    ports: 
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  redis_data:
